/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_camera2basic_Convert */
#include <android/log.h>

#define TAG "PengLog"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG ,__VA_ARGS__)
#ifndef _Included_com_example_android_camera2basic_Convert
#define _Included_com_example_android_camera2basic_Convert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_camera2basic_Convert
 * Method:    convert
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_com_smart_interview_main_camera_convert
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint);


JNIEXPORT void JNICALL Java_com_smart_interview_main_camera_convertByteToColor
        (JNIEnv *, jobject, jbyteArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
